services:
  - type: web
    name: cognee-api-weiwei
    env: python
    runtime: python-3.11.9  # AJOUT CRITIQUE pour Cognee
    region: oregon  # Optionnel: région plus proche Europe
    plan: starter   # Optionnel: plan gratuit
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn Process:app --host 0.0.0.0 --port $PORT --workers 1"
    healthCheckPath: "/health"  # NOUVEAU: Endpoint de santé
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"  # Version spécifique pour Cognee
      # Cognee configuration
      - key: LLM_API_KEY
        sync: false  # Render UI pour sécurité
      - key: OPENAI_API_KEY
        sync: false  # Render UI pour sécurité
      - key: COGNEE_ENABLED
        value: "true"
      # Performance
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."