services:
  - type: web
    name: cognee-api-weiwei
    env: python
    runtime: python-3.11.9
    region: oregon
    plan: starter
    
    # Build command CORRIGÉ pour résoudre les conflits
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir --force-reinstall fastapi uvicorn
      pip install --no-cache-dir -r requirements.txt
    
    # Start command optimisé
    startCommand: "python Process.py"
    
    # Health check
    healthCheckPath: "/health"
    
    # Variables d'environnement CRITIQUES
    envVars:
      # Python
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "."
      
      # API Keys (à configurer dans Render UI)
      - key: OPENAI_API_KEY
        sync: false
      - key: LLM_API_KEY
        sync: false
      
      # Cognee configuration (DÉSACTIVÉ par défaut)
      - key: COGNEE_ENABLED
        value: "false"
      
      # Optimisation mémoire pour Render
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      
      # Timeout pour éviter les blocages
      - key: WEB_CONCURRENCY
        value: "1"
      - key: MAX_WORKERS
        value: "1"